theme: jekyll-theme-slate
title: GrillBot
description: Discord bot
locale: "en-US"

markdown: redcarpet
redcarpet:
  extensions:
    - no_intra_emphasis
    - fenced_code_blocks
    - autolink
    - tables
    - strikethrough
    - superscript
    - with_to_data
