CREATE TABLE [dbo].[UnverifyLog]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	[Operation] INT NOT NULL,
	[FromUserID] VARCHAR(30) NOT NULL,
	[GuildID] VARCHAR(30) NOT NULL,
	[Datetime] DATETIME NOT NULL CONSTRAINT [DF_UnverifyLog_Datetime] DEFAULT (getdate()),
	[Data] VARCHAR(MAX) NOT NULL
)
