name: Publish release

on:
  release:
    branches: [master]
    types: [created]

jobs:
  ReleaseBuild:
    strategy:
      matrix:
        kind: ["Ubuntu", "Windows"]
        include:
          - kind: Ubuntu
            os: ubuntu-latest
            target: linux-x64
          - kind: windows
            os: windows-latest
            target: win-x64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.0
      - name: Build
        shell: bash
        run: |
          # Define some variables for things we need
          tag=$(git describe --tags --abbrev=0)
          bot_release_name="App-Bot-$tag-${{ matrix.target }}"
          math_release_name="App-Math-$tag-${{ matrix.target }}"

          # Build everything
          dotnet nuget add source -n "MyGet_DiscordNET_Prerelease" https://www.myget.org/F/discord-net/api/v3/index.json
          dotnet publish src/Grillbot/Grillbot.csproj --runtime "${{ matrix.target }}" -c Release -o "$bot_release_name"
          dotnet publish src/GrillBotMath/GrillBotMath.csproj --runtime "${{ matrix.target }}" -c Release -o "$math_release_name"

          if [ "${{ matrix.target }}" == "win-x64" ]; then
            7z a -tzip "${bot_release_name}.zip" "./${bot_release_name}/*"
            7z a -tzip "${math_release_name}.zip" "./${math_release_name}/*"
          else
            tar czvf "${bot_release_name}.tar.gz" "$bot_release_name"
            tar czvf "${math_release_name}.tar.gz" "$math_release_name"
          fi

          rm -rf "$bot_release_name"
          rm -rf "$math_release_name"
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "App*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
